name: Deploy

#when to run
on:
  push:
    branches:
      - main

#what jobs to do
jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy code
        run: npm run deploy